/**
* ------------------------------------------------------------------------------------------------
* @Name     POCH_Opportunity
* @Author   Mauricio Esquivel Cázares mesquivel@freewayconsulting.com
* @Date     Created: 2019-08-16
* @Group    POCH
* ------------------------------------------------------------------------------------------------
* @Related: POCH_OpportunityWithQuote
*
* |2019-08-12 mesquivel@freewayconsulting.com
*             Class creation.
* -----------------------------------------------------------------------------------------------
*/
public Interface POCH_IOpportunity {
    void updateOppValues(Map<string,string> mapFieldValue);
}